apiVersion: apps/v1
kind: Deployment
metadata:
  name: paella-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paella-app
  template:
    metadata:
      labels:
        app: paella-app
    spec:
      containers:
      - name: paella-app
        image: paella-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000