apiVersion: v1
kind: Service
metadata:
  name: paella-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000  # Adjusted to match containerPort from Deployment
    nodePort: 30007
  selector:
    app: paella-app  # Adjusted to match Deployment labels
